"""update users column comments

Revision ID: 36b487e4fc29
Revises: 7141741b0900
Create Date: 2026-01-27 18:03:37.888404

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "36b487e4fc29"
down_revision: Union[str, Sequence[str], None] = "7141741b0900"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "id",
        existing_type=sa.UUID(),
        comment="UUID пользователя",
        existing_comment="Уникальный ID пользователя",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=255),
        comment="Электронная почта пользователя (уникальна)",
        existing_comment="Электронная почта пользователя",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "username",
        existing_type=sa.VARCHAR(length=64),
        comment="Имя пользователя (уникально)",
        existing_comment="Имя пользователя",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Дата создания учетной записи пользователя",
        existing_comment="Дата регистрации пользователя",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Дата регистрации пользователя",
        existing_comment="Дата создания учетной записи пользователя",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users",
        "username",
        existing_type=sa.VARCHAR(length=64),
        comment="Имя пользователя",
        existing_comment="Имя пользователя (уникально)",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=255),
        comment="Электронная почта пользователя",
        existing_comment="Электронная почта пользователя (уникальна)",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "id",
        existing_type=sa.UUID(),
        comment="Уникальный ID пользователя",
        existing_comment="UUID пользователя",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
