"""create refresh sessions table

Revision ID: 7141741b0900
Revises: 6e524442961a
Create Date: 2026-01-27 17:54:59.235531

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7141741b0900"
down_revision: Union[str, Sequence[str], None] = "6e524442961a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refresh_sessions",
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
            comment="UUID записи refresh-сессии",
        ),
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="FK на users.id — владелец refresh-сессии",
        ),
        sa.Column(
            "refresh_token_hash",
            sa.String(length=255),
            nullable=False,
            comment="Хэш refresh-токена (не хранить токен в чистом виде)",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата истечения refresh-сессии",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания refresh-сессии",
        ),
        sa.Column(
            "revoked_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата отзыва refresh-сессии (если отозвана)",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_sessions_refresh_token_hash"),
        "refresh_sessions",
        ["refresh_token_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refresh_sessions_user_id"),
        "refresh_sessions",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refresh_sessions_user_id"), table_name="refresh_sessions")
    op.drop_index(
        op.f("ix_refresh_sessions_refresh_token_hash"),
        table_name="refresh_sessions",
    )
    op.drop_table("refresh_sessions")
    # ### end Alembic commands ###
